# Generated by Django 5.1.4 on 2025-01-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_alter_pizzamodel_pizza_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamodel',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Wednesday', max_length=9),
            preserve_default=False,
        ),
    ]
