# Generated by Django 5.1.4 on 2025-01-06 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_alter_pizzamodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzamodel',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100), django.core.validators.RegexValidator('^[A-Z][a-z]{,19}$', 'Only alpha characters are allowed. First character must be uppercase.')]),
        ),
        migrations.AlterField(
            model_name='pizzamodel',
            name='size',
            field=models.IntegerField(),
        ),
    ]
