# Generated by Django 5.1.4 on 2025-01-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0008_alter_pizzamodel_name_alter_pizzamodel_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
