# Generated by Django 5.1.4 on 2025-01-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0010_alter_pizzamodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzamodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
