# Generated by Django 5.1.4 on 2025-01-07 16:57

from django.db import migrations, models

import core.services.file_service


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0011_alter_pizzamodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzamodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.services.file_service.upload_pizza_photo),
        ),
    ]
