# Generated by Django 5.1.4 on 2025-01-01 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pizzamodel',
            table='pizzas',
        ),
    ]
