# Generated by Django 5.1.4 on 2025-01-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_alter_pizzamodel_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzamodel',
            options={'ordering': ('id',)},
        ),
    ]
